/**
 * rag.ts — Hybrid RAG pipeline
 *
 * PHASE 1:   BM25 + Cohere reranker + multi-query retrieval
 * PHASE 2:   Parent-child chunking + context compression + Redis cache
 * PHASE 1.5: HybridRetriever orchestrator replaces manual fan-out in
 *            chatWithAllMeetings, keeping all other logic intact.
 *
 * chatWithMeeting     — single-meeting scoped Q&A   (unchanged)
 * chatWithAllMeetings — global hybrid search         (refactored)
 */

import { prisma } from "./db"
import { chatWithAI, createEmbedding, createManyEmbeddings } from "./openai"
import { saveManyVectors, searchVectors } from "./pinecone"
import { chunkTranscriptParentChild, chunkTranscript, extractSpeaker } from "./text-chunker"
import { getCachedResponse, setCachedResponse } from "./cache"
import { createHybridRetriever } from "./retrieval/hybrid-retriever"
import { type RetrievedContext } from "./retrieval/types"
import Groq from "groq-sdk"

const groq = new Groq( { apiKey: process.env.GROQ_API_KEY! } )

// ─────────────────────────────────────────────
// CONSTANTS
// ─────────────────────────────────────────────

/**
 * Number of query variants generated by expandQuery.
 * All variants are forwarded to HybridRetriever for broader coverage.
 */
const MULTI_QUERY_N = 3

// ─────────────────────────────────────────────
// INGEST  — Phase 2: parent-child chunking
// (Unchanged — do not modify)
// ─────────────────────────────────────────────

export async function processTranscript (
  meetingId: string,
  userId: string,
  transcript: string,
  meetingTitle?: string
)
{
  // Use new parent-child chunker
  const childChunks = chunkTranscriptParentChild( transcript )

  if ( childChunks.length === 0 )
  {
    // Fallback to legacy chunker if transcript is too short to split
    const legacyChunks = chunkTranscript( transcript )
    const texts = legacyChunks.map( ( c ) => c.content )
    const embeddings = await createManyEmbeddings( texts )

    await prisma.transcriptChunk.createMany( {
      data: legacyChunks.map( ( c ) => ( {
        meetingId,
        chunkIndex: c.chunkIndex,
        content: c.content,
        speakerName: extractSpeaker( c.content ),
        vectorId: `${ meetingId }_chunk_${ c.chunkIndex }`,
        isChildChunk: false,
      } ) ),
      skipDuplicates: true,
    } )

    await saveManyVectors(
      legacyChunks.map( ( c, i ) => ( {
        id: `${ meetingId }_chunk_${ c.chunkIndex }`,
        embedding: embeddings[ i ],
        metadata: {
          meetingId,
          userId,
          chunkIndex: c.chunkIndex,
          content: c.content,
          speakerName: extractSpeaker( c.content ) ?? "",
          meetingTitle: meetingTitle ?? "Untitled Meeting",
          hasParent: false,
        },
      } ) )
    )
    return
  }

  // Embed only the small child contents → Pinecone gets precise chunks
  const texts = childChunks.map( ( c ) => c.content )
  const embeddings = await createManyEmbeddings( texts )

  // Store child chunks in DB — parentContent lives here, NOT in Pinecone
  await prisma.transcriptChunk.createMany( {
    data: childChunks.map( ( c ) => ( {
      meetingId,
      chunkIndex: c.chunkIndex,
      content: c.content,
      speakerName: extractSpeaker( c.content ),
      vectorId: `${ meetingId }_chunk_${ c.chunkIndex }`,
      parentContent: c.parentContent,
      parentChunkId: c.parentChunkId,
      isChildChunk: true,
    } ) ),
    skipDuplicates: true,
  } )

  await saveManyVectors(
    childChunks.map( ( c, i ) => ( {
      id: `${ meetingId }_chunk_${ c.chunkIndex }`,
      embedding: embeddings[ i ],
      metadata: {
        meetingId,
        userId,
        chunkIndex: c.chunkIndex,
        content: c.content,
        speakerName: extractSpeaker( c.content ) ?? "",
        meetingTitle: meetingTitle ?? "Untitled Meeting",
        parentChunkId: c.parentChunkId ?? "",
        hasParent: true,
      },
    } ) )
  )
}

// ─────────────────────────────────────────────
// SINGLE-MEETING CHAT  (Unchanged)
// ─────────────────────────────────────────────

export async function chatWithMeeting (
  userId: string,
  meetingId: string,
  question: string
)
{
  const questionEmbedding = await createEmbedding( question )

  const results = await searchVectors(
    questionEmbedding,
    { userId, meetingId },
    5
  )

  const meeting = await prisma.meeting.findUnique( { where: { id: meetingId } } )

  const context = results
    .map( ( r ) => `${ r.metadata?.speakerName || "Unknown" }: ${ r.metadata?.content || "" }` )
    .join( "\n\n" )

  const systemPrompt = `You are helping someone understand their meeting.
Meeting: ${ meeting?.title || "Untitled Meeting" }
Date: ${ meeting?.createdAt ? new Date( meeting.createdAt ).toDateString() : "Unknown" }

Here's what was discussed:
${ context }

Answer the user's question based only on the meeting content above. If the answer isn't in the meeting, say so.`

  const answer = await chatWithAI( systemPrompt, question )

  return {
    answer,
    sources: results.map( ( r ) => ( {
      meetingId: r.metadata?.meetingId,
      content: r.metadata?.content,
      speakerName: r.metadata?.speakerName,
      confidence: r.score,
    } ) ),
  }
}

// ─────────────────────────────────────────────
// MULTI-QUERY EXPANSION  (Unchanged)
// ─────────────────────────────────────────────

async function expandQuery ( question: string ): Promise<string[]>
{
  try
  {
    const response = await groq.chat.completions.create( {
      model: "llama-3.3-70b-versatile",
      temperature: 0.6,
      max_tokens: 200,
      response_format: { type: "json_object" },
      messages: [
        {
          role: "system",
          content: `Generate ${ MULTI_QUERY_N } distinct rephrasings of the user's question.
Each rephrasing should approach the same information need from a different angle.
Return ONLY valid JSON: { "queries": ["query1", "query2", "query3"] }`,
        },
        { role: "user", content: question },
      ],
    } )

    const raw = response.choices[ 0 ]?.message?.content || "{}"
    const parsed = JSON.parse( raw ) as { queries?: string[] }
    const variants = parsed.queries ?? []

    // Always include the original at index 0 (HybridRetriever uses queries[0]
    // as the canonical Cohere rerank query)
    return [ question, ...variants ].slice( 0, MULTI_QUERY_N + 1 )
  } catch ( err )
  {
    console.warn( "⚠️ Multi-query expansion failed, using original:", err )
    return [ question ]
  }
}

// ─────────────────────────────────────────────
// PROMPT BUILDER
// Converts the clean RetrievedContext[] from HybridRetriever into
// the system prompt consumed by chatWithAI.
// ─────────────────────────────────────────────

/**
 * Build the LLM system prompt from hybrid retrieval results.
 *
 * Token budget notes (llama-3.3-70b-versatile free tier: 12 K TPM):
 *   System prompt overhead ≈ 300 tokens
 *   Question             ≈ 100 tokens
 *   → ~3 000 tokens / ~12 000 chars left for context
 *
 * The compressor already enforced a 3 000-token cap on the contexts array,
 * so we just need a light character guard on the graph knowledge snippet.
 */
function buildSystemPrompt (
  contexts: RetrievedContext[],
  graphKnowledge: string | null
): string
{
  const MAX_GRAPH_CHARS = 1_200
  const MAX_CONTEXT_CHARS = 5_000

  const graphKnowledgeCapped = ( graphKnowledge ?? "" ).slice( 0, MAX_GRAPH_CHARS )

  const contextLines: string[] = []
  let budgetLeft = MAX_CONTEXT_CHARS

  for ( const ctx of contexts )
  {
    const title = String( ctx.metadata?.meetingTitle ?? "Untitled Meeting" )
    const speaker = String( ctx.metadata?.speakerName ?? "Unknown" )

    // [★] marker: the original rag.ts used source === "both" (CandidateDoc).
    // In RetrievedContext we track the originating adapter per item.
    // We replicate the spirit of the marker by flagging graph + vector overlap.
    const isCrossSource = ctx.source === "graph"
    const tag = isCrossSource ? " [★]" : ""

    const line = `[${ title }]${ tag } ${ speaker }: ${ ctx.content }`

    if ( line.length >= budgetLeft )
    {
      if ( contextLines.length === 0 )
      {
        contextLines.push( line.slice( 0, budgetLeft ) + "…" )
      }
      break
    }

    contextLines.push( line )
    budgetLeft -= line.length + 2  // +2 for "\n\n" separator
    if ( budgetLeft <= 0 ) break
  }

  const vectorContext = contextLines.join( "\n\n" )

  return `You are an AI assistant with access to corporate meeting memory.

KNOWLEDGE GRAPH (structured facts):
${ graphKnowledgeCapped || "No graph data." }

TRANSCRIPT EXCERPTS (raw discussion):
${ vectorContext }

Instructions:
- Synthesise both sources to answer accurately.
- [★] means the excerpt came from the knowledge graph — highly reliable for named entities and structured facts.
- If sources conflict, the transcript is the ground truth.
- If the answer is not in either source, say so clearly.`
}

// ─────────────────────────────────────────────
// UPGRADED: GLOBAL HYBRID CHAT  (Phase 1.5)
// ─────────────────────────────────────────────

export async function chatWithAllMeetings ( userId: string, question: string )
{
  console.log( `🧠 Hybrid RAG: "${ question }"` )

  // ── Redis cache check ───────────────────────────────────────────────────────
  const cached = await getCachedResponse( question, userId )
  if ( cached )
  {
    console.log( "⚡ Cache hit" )
    return { answer: cached, sources: [], fromCache: true }
  }

  // ── Multi-query expansion ───────────────────────────────────────────────────
  const queries = await expandQuery( question )
  console.log( `📝 Query variants: ${ queries.length }` )

  // ── HybridRetriever — replaces manual fan-out, merge, rerank, compress ─────
  //
  //  Internally executes:
  //    1. VectorRetriever + BM25Retriever + GraphRetriever in parallel
  //       for every query variant.
  //    2. ID-level dedup (keeps highest-scoring entry per chunk).
  //    3. Unified scoring: source-weight × semantic × temporal decay.
  //    4. compressRetrievals: trigram Jaccard dedup → Cohere rerank → token trim.
  //
  const retriever = createHybridRetriever()
  const contexts = await retriever.retrieve( queries, userId )

  console.log( `🗜️  Final context: ${ contexts.length } chunks for prompt` )

  // ── Extract graph knowledge from graph-sourced contexts ────────────────────
  //
  // The GraphRetriever produces RetrievedContext items whose metadata may carry
  // a pre-formatted "graphSummary" string (set by the adapter).  If present we
  // surface it in the dedicated KNOWLEDGE GRAPH section of the prompt; if not,
  // graph chunks are treated the same as transcript chunks.
  //
  const graphKnowledge =
    contexts
      .filter( ( ctx ) => ctx.source === "graph" && ctx.metadata?.graphSummary )
      .map( ( ctx ) => String( ctx.metadata.graphSummary ) )
      .join( "\n" ) || null

  // ── Build prompt & generate answer ────────────────────────────────────────
  const systemPrompt = buildSystemPrompt( contexts, graphKnowledge )
  const answer = await chatWithAI( systemPrompt, question )

  // ── Cache the answer ───────────────────────────────────────────────────────
  await setCachedResponse( question, answer, userId )

  return {
    answer,
    fromCache: false,
    sources: contexts.map( ( ctx ) => ( {
      meetingId: ctx.metadata?.meetingId,
      meetingTitle: ctx.metadata?.meetingTitle,
      content: ctx.content,
      speakerName: ctx.metadata?.speakerName,
      confidence: ctx.confidenceScore,
      source: ctx.source,
    } ) ),
    debug: {
      queryVariants: queries,
      finalDocs: contexts.length,
    },
  }
}